version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: event-management-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
